# Linear algebra

In [79]:
import numpy as np

In [80]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [81]:
a[0]

1

In [82]:
a.shape

(3,)

Element-wise(also known as the Hadamard product) multiplication using loop

In [83]:
n = a.shape[0]
res = np.zeros(shape=n)
for i in range(n):
    res[i] = a[i] * b[i]
print(res)


[ 4. 10. 18.]


Element-wise multiplication using opeartor

In [84]:
a * b

array([ 4, 10, 18])

## Dot Product

Calculate dot product using loop

In [85]:
n = a.shape[0]
res = 0
for i in range(n):
    res += a[i] * b[i]
print(res)

32


Calculate dot product using in-built function

In [86]:
np.dot(a,b)

32

Using @ opeartor

In [87]:
a @ b

32

In [88]:
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [89]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [90]:
a.shape,b.shape

((2, 3), (3, 2))

In [91]:
np.matmul(a,b)

array([[22, 28],
       [49, 64]])

### Transpose

In [ ]:
a

In [92]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [94]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
r,c = a.shape
a_t = np.zeros(shape=(c,r),dtype=int)
row,col = 0,0
for i in range(c):
    col = 0
    for j in range(r):
        a_t[row][col] = a[j][i]
        col +=1
    row +=1
a_t

array([[1, 4],
       [2, 5],
       [3, 6]])

## EigenValue

A - (lambda * I) = 0

In [99]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [100]:
I = np.array([[1,0],[0,1]])