In [59]:
import numpy as np

You have a dataset with three features (columns) and four data points (rows). Construct a 
4×3 matrix to represent this data. How would adding a bias term modify this matrix?

In [60]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original Matrix:\n {a}")
print(f"Modified array after adding bias term:\n {a+2}")

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Modified array after adding bias term:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Q3: Construct two matrices,A and 𝐵 of shapes 3×2 and 2×3 respectively. Compute the product AB and describe the result.
Can you compute BA? Why or why not?



In [61]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])
a, b

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [64]:

rows_a = a.shape[0]
cols_a = a.shape[1]
cols_b = b.shape[1]

result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]

for i in range(rows_a):
    for j in range(cols_b):
        for k in range(cols_a):
            result[i][j] += a[i][k] * b[k][j]
result

[[9, 12, 15], [19, 26, 33], [29, 40, 51]]

In [63]:
np.dot(a, b)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])